repos:
- repo: https://github.com/nicklockwood/SwiftFormat.git
  rev: 0.48.1
  hooks:
  - id: swiftformat

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
  - id: pretty-format-json
  - id: check-json
  - id: check-yaml

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: insert-license
    files: ^Sources/(.*).swift$
    args:
    - --license-filepath
    - LICENSE_HEADER
    - --comment-style
    - //
