os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.2

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - swift build

notifications:
  email:
    on_success: never
    on_failure: change
