on: 
  push:

name: Build
jobs:
  checks:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.0.0

    - name: build
      uses: cedrickring/golang-action@1.7.0
